### ISSUE TITLE
Would it be possible to reduce the size of the package ?

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [jannikmi/timezonefinder#116]
Hello, thank you for creating this package, very useful.

I was wondering if it would theoretically be possible to reduce the size of the package ? I see that `poly_data.bin` weight more than 50 megabytes ? Maybe with a lower "good enough" polygon count ?

Thank you in advance for any tips you might provide :) 
`

**Comment by jannikmi** [comment]
Please consider using the class `TimezonefinderL`, since then all the binary files can be deleted (cf. https://timezonefinder.readthedocs.io/en/latest/1_usage.html#timezonefinderl).

In the past I have tested simplifying the timezone polygons (their geometry), but this approach was infeasible.
I hope this helps. If not, feel free to reopen this issue.

**Comment by Toreno96** [comment]
@jannikmi Would it be feasible for you to maintain a separate flavor of the package, something like `timezonefinder-slim` with the binary files pre-deleted and other requirements pre-configured? 🙏

**Comment by jannikmi** [comment]
That was exactly the idea behind my (deprecated) package 'timezonefinderL'. At some point however I decided that the effort for maintaining a package with so much redundancy was too high documentation etc.). Of course feel free to create a merge request to update the repository/package.

**Comment by Toreno96** [comment]
OK, thanks for the quick answer.
