### ISSUE TITLE
Performance issues on Versions from 6.x.x to latest 

### ISSUE THREAD

**Issue by Juankimr** [jannikmi/timezonefinder#158]
Im having performance issues on versions in versions greater than 5.2.0 something changed on the code that have created a bottleneck that does not allow the use of the library i add 2 screens with the profiled issue
This is the same code with versions 

6.1.3
![image](https://user-images.githubusercontent.com/7659750/192460435-e1ec71d3-7322-4bb5-8d97-5b6ce3d49382.png)

5.2.0
![image](https://user-images.githubusercontent.com/7659750/192459767-3f88ca1e-5eac-40fe-bd58-56f9652c11a7.png)

you can check that on version 6.1.3 it takes 3,381 on read_shortcuts_binary unlike version 5.2.0 that takes 0.082 to run completely

**Comment by jannikmi** [comment]
Since version 6 the "shortcut" binary file is being read into memory during initialisation.
It is therefore important to initialise a `Timezonefinder` instance only once and reuse it for all queries.

From the documentation:
``` python
from timezonefinder import TimezoneFinder

tf = TimezoneFinder()  # reuse

query_points = [(13.358, 52.5061), ...]
for lng, lat in query_points:
    tz = tf.timezone_at(lng=lng, lat=lat)  # 'Europe/Berlin'
```

Here are some speed benchmark results:
https://timezonefinder.readthedocs.io/en/latest/7_performance.html

Please let me know if the performance still is unsatisfactory for your use case.
