### ISSUE TITLE
Bump h3 version

### ISSUE THREAD

**Issue by dylankbuckley** [jannikmi/timezonefinder#207]
h3 pre-release: [https://pypi.org/project/h3/4.0.0b2/](https://pypi.org/project/h3/4.0.0b2/). bumping to avoid conflicts with projects using latest h3 versions

**Comment by jannikmi** [comment]
Thanks for bringing this up. 
It seems like v4 introduces a lot of breaking changes:
```
FAILED tests/shortcut_test.py::test_resolutions - AttributeError: module 'h3.api.numpy_int' has no attribute 'h3_get_resolution'
FAILED tests/shortcut_test.py::test_unique_pole_cells - AttributeError: module 'h3.api.numpy_int' has no attribute 'h3_get_resolution'
```

I think at the moment it is too early to force h3>=4
Would you be willing to raise a PR for supporting both v3 and v4 API?

**Comment by dylankbuckley** [comment]
Yeah - I should have some time to work on this tomorrow.

**Comment by jannikmi** [comment]
Great!
Ideally you could also add tests for both h3 versions (ensuring to test backward compatibility)

**Comment by Gui-FernandesBR** [comment]
Hey, I recently tried to install `timezonefinder` on python 3.12 but it is not working due to a wheel problem of h3 package.
I've opened up an issue in their repo (https://github.com/uber/h3-py/issues/326), attaching here to follow-up.

Given the above error, the timezonefinder project cannot be built on Python 3.12 yet.
Shall we open another issue here to address people having the same installation problem on 3.12?

**Comment by jannikmi** [comment]
Please open another issue for python 3.12 compatibility. Let's see if there are other problems apart from the h3 related build errors. We can keep track of the progress there.

**Comment by jannikmi** [comment]
@dylankbuckley Do you have any time to look into this?

**Comment by elbarbi** [comment]
Hi everyone, 
I am using both H3 and timezone finder. How's the issue progressing ?
I can maybe try to contribute on this issue.

**Comment by jannikmi** [comment]
Hello @elbarbi, so far no related PR has been raised. Any contribution would be highly appreciated!
