### ISSUE TITLE
investigate shortcut precision

### ISSUE THREAD

**Issue by jannikmi** [jannikmi/timezonefinder#90]
build evaluation tool on speed and size impact ("heatmap") of varying the shortcut size
decide for best option. tradeoff!

**Comment by MrMinimal64** [comment]
try out other methods for "indexing" timezone polygons. 
Ideas:
- map "voxels" to polygon ids
- decision tree, pruning depending on performance requirements
...

**Comment by MrMinimal64** [comment]
note: the sole purpose of shortcuts is too speed up the lookup process of candidate polygons and while at the same time limiting the amount of polygons to check. it is most favorable to receive only polygons from a single zone to return this zone straight away.
all shortcut methods must be evaluated with these thoughts in mind.

**Comment by ringsaturn** [comment]
I suggest to use Uber H3 to represent some areas. From our production usage of administration search, exclude 2~3 layers at edge will decrease 90%+ polygon search times but comes with lot’s memory cost. Use mmap may help, but still expensive.

**Comment by jannikmi** [comment]
Thanks for the suggestion. H3 looks promising and it even has a python SDK! I will definitely look into it.

**Comment by jannikmi** [comment]
`timezonefinder` is using `h3` for timezone polygon indexing since version `6.0.0` (#133)

**Comment by ringsaturn** [comment]
Hi, I am doing a similar thing in Golang, and I found that using tile index from web map may be a good idea.

1. It's simple. Each tile key is just 3 int: X/Y/Z. While H3 is too complex, although it can be truncated via bitwise operation like [PlaceKey](https://docs.placekey.io/Placekey_Technical_White_Paper.pdf)
2. Each tile can be devided into 4 children, because it's built on Quadtree. And H3’s upper hex can not just cover all lower nodes.

Here is a demo using tile to index timezone shape:

<img width="1920" alt="Screenshot 2022-11-06 at 17 15 09" src="https://user-images.githubusercontent.com/13536789/200174943-7d40661e-bda5-4b79-a867-ec637e245a49.png">

**Comment by jannikmi** [comment]
@ringsaturn thanks for letting me know. your input is very valuable and helpful!

Have you made any comparsisons between the h3 and the web map tile index? If so, could you please share the results?
What are the downsides of using h3 in your use case? what are you trying to impove using the other indexing method?
